<?php

$dictionary['Lead']['fields']['lead_status'] = array (
      'required' => false,
      'name' => 'lead_status',
      'vname' => 'LBL_LEAD_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_status_list',
      'studio' => 'visible',
      'dependency' => false,
    );

$dictionary['Lead']['fields']['lead_sex'] = array (
      'required' => false,
      'name' => 'lead_sex',
      'vname' => 'LBL_LEAD_SEX',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_sex_list',
      'studio' => 'visible',
      'dependency' => false,
    );

$dictionary['Lead']['fields']['resident'] = array (
      'required' => false,
      'name' => 'resident',
      'vname' => 'LBL_RESIDENT',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['inn']=array (
      'required' => false,
      'name' => 'inn',
      'vname' => 'LBL_INN',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'индивидаульный налоговый номер',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '15',
      'size' => '20',
    );

$dictionary['Lead']['fields']['date_birthday'] = array (
      'required' => false,
      'name' => 'date_birthday',
      'vname' => 'LBL_DATE_BIRTHDAY',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );

$dictionary['Lead']['fields']['soc_status'] = array (
      'required' => false,
      'name' => 'soc_status',
      'vname' => 'LBL_SOC_STATUS',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_socstatus_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
    );


$dictionary['Lead']['fields']['statliveplace'] = array (
      'required' => false,
      'name' => 'statliveplace',
      'vname' => 'LBL_STATUS_LIVEPLACE',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_statliveplace_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
    );

$dictionary['Lead']['fields']['education'] = array (
      'required' => false,
      'name' => 'education',
      'vname' => 'LBL_EDUCATION',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_education_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['photo'] = array (
      'required' => false,
      'name' => 'photo',
      'vname' => 'LBL_PHOTO',
      'type' => 'image',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Выберите фотографию',
      'help' => 'Выберите фотографию',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 255,
      'size' => '20',
      'studio' => 'visible',
      'dbType' => 'varchar',
      'border' => '1',
      'width' => '120',
      'height' => '240',
    );


$dictionary['Lead']['fields']['ukrpasport_nom'] = array (
      'required' => false,
      'name' => 'ukrpasport_nom',
      'vname' => 'LBL_UKRPASPORT_NOM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Серия Номер паспорта Украины',
      'help' => 'Серия Номер паспорта Украины',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
);


$dictionary['Lead']['fields']['ukrpas_kemvidan'] = array (
      'required' => false,
      'name' => 'ukrpas_kemvidan',
      'vname' => 'LBL_UKRPASP_KEMVIDAN',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Украинский паспорт кем выдан',
      'help' => 'Украинский паспорт кем выдан',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['ukrpas_datavidachy'] = array (
      'required' => false,
      'name' => 'ukrpas_datavidachy',
      'vname' => 'LBL_UKRPASP_DATAVIDACHY',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Украинский паспорт дата выдачи',
      'help' => 'Украинский паспорт дата выдачи',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );


$dictionary['Lead']['fields']['placebirth']=array (
      'required' => false,
      'name' => 'placebirth',
      'vname' => 'LBL_PLACEBIRTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Место рождения',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '30',
      'size' => '20',
    );


$dictionary['Lead']['fields']['zagrpasport_nom'] = array (
      'required' => false,
      'name' => 'zagrpasport_nom',
      'vname' => 'LBL_ZAGPASPORT_NOM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Серия Номер загран паспорта Украины',
      'help' => 'Серия Номер загран паспорта Украины',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
);

$dictionary['Lead']['fields']['zagrpas_kemvidan'] = array (
      'required' => false,
      'name' => 'zagrpas_kemvidan',
      'vname' => 'LBL_ZAGRPASP_KEMVIDAN',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => ' Заграничный Украинский паспорт кем выдан',
      'help' => 'Заграничный Украинский паспорт кем выдан',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['zagrpas_datavidachy'] = array (
      'required' => false,
      'name' => 'zagrpas_datavidachy',
      'vname' => 'LBL_ZAGRPASP_DATAVIDACHY',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Загран паспорт дата выдачи',
      'help' => 'Загран паспорт дата выдачи',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );